// GPT-powered storyboard generator for Veo video ads.
//
// Replaces the hardcoded 3-beat motion arc + fixed "slow z-axis push-in"
// camera move in veoPromptBuilder with a per-ad storyboard composed by
// GPT from concept + brand + product + scene context. Output is a
// structured { camera, audio, beats[], vibe } object the prompt builder
// splices into the Veo prompt.
//
// Off by default — flip VEO_USE_GPT_STORYBOARD=true to enable. When off
// or when the GPT call fails, veoPromptBuilder falls back to the
// hardcoded storyboard so the render path stays unblocked.
//
// The seed image carries the SCENE; this service only directs MOTION,
// CAMERA, and AUDIO. Compositing constraints (no text, anatomy,
// product fidelity) stay in veoPromptBuilder regardless.

const OpenAI = require('openai');
const { trackLlmCall } = require('./costTracker');
const { archetypeDescription } = require('./veoPromptBuilder');

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const MODEL_ID    = 'gpt-4o-mini';
const TEMPERATURE = 0.85;   // creative variance is the whole point of this service
const MAX_TOKENS  = 600;

function enabled() {
  return String(process.env.VEO_USE_GPT_STORYBOARD || '').toLowerCase() === 'true';
}

const RESPONSE_SCHEMA = {
  name:   'veo_storyboard',
  strict: true,
  schema: {
    type: 'object',
    additionalProperties: false,
    required: ['camera', 'audio', 'beats', 'vibe'],
    properties: {
      camera: {
        type:        'string',
        description: 'One camera move for the entire 5-second shot — e.g. "slow dolly-in", "lateral truck right to left", "static lock-off with subtle handheld drift", "slow orbit clockwise", "slow pull-back reveal". Keep it singular and disciplined.'
      },
      audio: {
        type:        'string',
        description: 'One line of audio direction — natural ambience + optional musical or sonic cue. No voices, no dialogue, no narration.'
      },
      beats: {
        type:     'array',
        minItems: 2,
        maxItems: 4,
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['time', 'description'],
          properties: {
            time:        { type: 'string', description: 'Time range like "0:00–0:02"' },
            description: { type: 'string', description: 'Motion + camera direction for this beat. No scene content (the seed image has it). No text/overlay direction (chrome lands later).' }
          }
        }
      },
      vibe: {
        type:        'string',
        description: '2–4 words capturing the energy — e.g. "editorial, warm, quiet".'
      }
    }
  }
};

function buildSystemPrompt() {
  return [
    'You are a creative director writing the motion and camera direction for a 5-second AI-generated product video.',
    'The video is generated by Veo 3.1 in image-to-video mode — a seed image already establishes the scene, composition, lighting, and subject.',
    'Your job is to direct MOTION, CAMERA, and AUDIO only. Do NOT describe what is in the frame — the seed image carries that.',
    '',
    'HARD RULES:',
    '- Single continuous shot. No cuts, no scene changes, no time jumps.',
    '- Total runtime is exactly 5 seconds.',
    '- Motion must stay subtle — premium product video, not a dynamic montage. Over-driving motion warps products, fabrics, and faces.',
    '- The video will have animated text/CTA overlays composited on top later. Do NOT direct any text, typography, or graphic overlays.',
    '- Audio is generated natively by Veo. Direct ambience + at most one subtle musical/sonic cue. NEVER include voices, dialogue, or narration.',
    '- Camera is ONE move for the full shot. Pick whichever fits the concept best — slow push-in, lateral truck, static lock-off with micro-drift, slow orbit, slow pull-back-reveal, or your own variation.',
    '- Beat descriptions are tight and physical: what does the camera do, what does the subject do, what does the light do. No narrative, no emotional adjectives in the beats.',
    '- Vary your structure. Don\'t default to the same 3-beat establish→motion→push-in template every time.',
    '',
    'OUTPUT a JSON object matching the provided schema.'
  ].join('\n');
}

function buildUserPrompt({ concept, brand, product, scene, lighting, mood, subject, aspectRatio, operatorPrompt }) {
  const lines = [];
  lines.push(`Product: ${product?.title || '(untitled product)'}`);
  if (product?.description) lines.push(`Product description: ${product.description}`);

  if (brand?.tone?.length)  lines.push(`Brand voice: ${brand.tone.slice(0, 5).join(', ')}`);
  if (brand?.tagline)       lines.push(`Brand essence: "${brand.tagline}"`);

  if (concept?.archetype) {
    lines.push(`Concept archetype: ${concept.archetype} — ${archetypeDescription(concept.archetype)}`);
  }
  if (concept?.emotional_hook) lines.push(`Emotional hook: ${concept.emotional_hook}`);
  if (concept?.social_proof_type && concept.social_proof_type !== 'none' && concept.social_proof_type !== 'absent') {
    lines.push(`Social proof angle: ${concept.social_proof_type}`);
  }

  if (scene)    lines.push(`Scene: ${scene}`);
  if (lighting) lines.push(`Lighting: ${lighting}`);
  if (mood)     lines.push(`Mood: ${mood}`);

  if (subject?.label) {
    const posText = subject.hPos ? ` framed on the ${subject.hPos} side` : '';
    lines.push(`Primary subject: ${subject.label}${posText}`);
  }

  lines.push(`Aspect ratio: ${aspectRatio}`);

  if (operatorPrompt && String(operatorPrompt).trim()) {
    lines.push('');
    lines.push(`OPERATOR REFINEMENT (must be honored): ${String(operatorPrompt).trim()}`);
  }

  lines.push('');
  lines.push('Write the storyboard.');
  return lines.join('\n');
}

// Resolves the structured context veoPromptBuilder pulls from
// (LayoutInputArtifact + detect-pipeline sourceMedia) into the flat
// fields the storyboard prompt expects.
function resolveContext({ concept, brand, product, layoutInput, sourceMedia, subject, aspectRatio, operatorPrompt }) {
  const scene =
    layoutInput?.media?.background_description
    || [sourceMedia?.background?.setting, sourceMedia?.background?.scene_type, sourceMedia?.background?.style]
        .filter(Boolean)
        .filter((v, i, arr) => arr.indexOf(v) === i)
        .join(', ')
    || null;

  const lighting = layoutInput?.media?.background_lighting
    || sourceMedia?.background?.lighting
    || null;

  const moods = Array.isArray(sourceMedia?.background?.mood) ? sourceMedia.background.mood.filter(Boolean) : [];
  const mood  = moods.length ? moods.slice(0, 3).join(', ') : (layoutInput?.media?.background_style || null);

  return { concept, brand, product, scene, lighting, mood, subject, aspectRatio, operatorPrompt };
}

// Main export. Returns structured storyboard or null on failure / when
// the flag is off. Callers must handle null and fall back to the
// hardcoded storyboard in veoPromptBuilder.
async function generateStoryboard({
  concept       = null,
  brand         = null,
  product       = null,
  layoutInput   = null,
  sourceMedia   = null,
  subject       = null,
  aspectRatio   = '1:1',
  operatorPrompt = null,
  brandId       = null,
  productId     = null
} = {}) {
  if (!enabled()) return null;
  if (!process.env.OPENAI_API_KEY) {
    console.warn('🎬 veoStoryboard: OPENAI_API_KEY missing — falling back to hardcoded storyboard');
    return null;
  }

  const ctx = resolveContext({ concept, brand, product, layoutInput, sourceMedia, subject, aspectRatio, operatorPrompt });
  const system = buildSystemPrompt();
  const user   = buildUserPrompt(ctx);

  const t0 = Date.now();
  try {
    const completion = await trackLlmCall(
      {
        stage:      'veo_storyboard',
        provider:   'openai',
        model:      MODEL_ID,
        purposeTag: 'veo',
        brandId, productId,
        visionImages: 0,
        cacheKey:   null   // per-ad, not cached — variance is the goal
      },
      () => openai.chat.completions.create({
        model:           MODEL_ID,
        response_format: { type: 'json_schema', json_schema: RESPONSE_SCHEMA },
        messages: [
          { role: 'system', content: system },
          { role: 'user',   content: user }
        ],
        temperature: TEMPERATURE,
        max_tokens:  MAX_TOKENS
      })
    );

    const raw = completion.choices?.[0]?.message?.content;
    if (!raw) throw new Error('storyboard returned no content');

    const parsed = JSON.parse(raw);
    const elapsedMs = Date.now() - t0;
    console.log(
      `🎬 veoStoryboard: camera="${parsed.camera}" beats=${parsed.beats?.length || 0} ` +
      `vibe="${parsed.vibe}" took=${elapsedMs}ms`
    );
    return parsed;
  } catch (err) {
    const elapsedMs = Date.now() - t0;
    console.warn(`⚠️  veoStoryboard: failed after ${elapsedMs}ms (${err.message}) — falling back to hardcoded storyboard`);
    return null;
  }
}

module.exports = { generateStoryboard, enabled };
